development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:1abfe4da41ef06609ce5f62823ab2ebc@pearlfish.redistogo.com:9105/
  channel_prefix: Message_me_app_production
